language: java
before_script: 
    - sudo wget -q http://dl.google.com/android/android-sdk_r18-linux.tgz 
    - sudo tar xzvf android-sdk_r18-linux.tgz > /dev/null
    - sudo android-sdk-linux/tools/android -s update sdk --filter android-7,platform-tool --no-ui
    - sudo android-sdk-linux/tools/android -s update project --path ./TomatoMonitor --target "android-7"
    - sudo chmod -R 777 ./*
script: "./buildstuff.sh"